# Generated by Django 5.1.7 on 2025-03-20 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelroom_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
